[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
demo_anchor = "HHNX8M8WDW5PtAGtfAiTqQwaXas3DsREXk7ZDkS9JMBZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test1.ts"
